[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/julienschmidt/httprouter"
  version = "1.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/Roverr/hotstreak"

[[constraint]]
  name = "github.com/kelseyhightower/envconfig"
  version = "1.3.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.2.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"

[[constraint]]
  name = "github.com/rs/cors"
  version = "1.6.0"

[[constraint]]
  name = "github.com/kennygrant/sanitize"
  version = "1.2.4"

[[constraint]]
  name = "github.com/brianvoe/gofakeit"
  version = "3.15.0"

[[constraint]]
  name = "github.com/dgrijalva/jwt-go"
  version = "3.2.0"

[[constraint]]
  name = "github.com/natefinch/lumberjack"
  version = "2.1.0"
